n = input('Digite algo:')
print('O tipo primitivo desse valor é da'.format(type(n)))
print('São maiúsculas? {}'.format(n.isupper()))
print('É númerico? {}'.format(n.isnumeric()))
print('É alfanumérico? {}'.format(n.isalnum()))
print('É alfabético? {}'.format(n.isalpha()))
print('ASCII? {}'.format(n.isascii()))
print('Todos os caracteres são decimais? {}'.format(n.isdecimal()))
print('São minúsculas? {}'.format(n.islower()))
print('Dígito? {}'.format(n.isdigit()))
print('É um identificador válido? {}'.format(n.isidentifier()))
print('Os caracteres são imprimíveis? {}'.format(n.isprintable()))
print('São apenas espaços? {}'.format(n.isspace()))
print('Capitalizada? {}'.format(n.istitle()))
print("Já foram apresntadas todas as possíveis informações")
print("Disponível para críticas construtivas")
